
readingDataPointsFilters:
  - MinDistDataPointsFilter:
      minDist: 1
  - RandomSamplingDataPointsFilter:
      prob: 0.5

referenceDataPointsFilters:
  - MinDistDataPointsFilter:
      minDist: 1
  - RandomSamplingDataPointsFilter:
      prob: 0.65

matcher:
  KDTreeMatcher:
    knn: 10
    epsilon: 0

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.95

errorMinimizer:
  PointToPointErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 3000
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4

inspector:
  VTKFileInspector

logger:
#  FileLogger
  NullLogger
